import { useCallback, useEffect, useState } from "react";
import { Activity, ArrowRight, Ban, Check, ChevronRight, CircleDot, Clock3, FileKey2, Fingerprint, Gauge, ListTree, LockKeyhole, Play, RefreshCw, ShieldCheck, ShoppingBag, SquareArrowOutUpRight, TriangleAlert, UserCheck, X } from "lucide-react";

type View = "overview" | "issue" | "mandate" | "simulator" | "stepup" | "audit";
type Product = { id:string; merchant_id:string; name:string; price_paise:number; currency:string; category:string; condition:string; active:boolean; attributes:Record<string, unknown> };
type Mandate = { id:string; instruction_text:string; hard_constraints:Record<string, unknown>; semantic_constraints:{id:string;text:string}[]; status:string; version:number; expires_at:string; max_executions:number; execution_count:number; signature:string; created_at:string; revoked_at:string|null };
type HardCheck = { name:string; passed:boolean; expected:unknown; actual:unknown; source:string };
type SemanticResult = { constraint_id:string; status:string; evidence:{field:string;value:unknown;source:string}[]; reason:string };
type Decision = { decision:"ALLOW"|"BLOCK"|"STEP_UP"; reason_code:string|null; proposal_id:string; step_up_id:string|null; hard_gate:{status:string;reason_code:string|null;checks:HardCheck[]}; semantic:{results:SemanticResult[];service_status:string}|null };
type AuditEvent = { id:string; event_type:string; entity_id:string; payload:Record<string,unknown>; created_at:string };
type Draft = { instruction_text:string; hard_constraints:Record<string,unknown>|null; semantic_constraints:{id:string;text:string}[]; unresolved:{field:string;reason:string}[] };

const API = import.meta.env.VITE_API_URL ?? "";
const defaultInstruction = "Buy noise-cancelling headphones under ₹20k. Nothing refurbished. Good for travel. Nothing flashy.";
const nav: {id:View;label:string;icon:typeof Gauge}[] = [
  {id:"overview",label:"Control room",icon:Gauge}, {id:"issue",label:"Issue mandate",icon:FileKey2}, {id:"mandate",label:"Mandate detail",icon:Fingerprint},
  {id:"simulator",label:"Agent checkout",icon:ShoppingBag}, {id:"stepup",label:"Human step-up",icon:UserCheck}, {id:"audit",label:"Audit trail",icon:ListTree},
];
async function request<T>(path:string, init?:RequestInit):Promise<T> {
  const response = await fetch(`${API}${path}`, {headers:{"Content-Type":"application/json", ...init?.headers}, ...init});
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body?.detail?.reason_code ?? body?.detail?.message ?? `HTTP ${response.status}`);
  return body as T;
}
const money = (paise:number) => new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR",maximumFractionDigits:0}).format(paise/100);
const when = (value:string) => new Intl.DateTimeFormat("en-IN", {hour:"2-digit",minute:"2-digit",second:"2-digit",day:"2-digit",month:"short"}).format(new Date(value));
const pretty = (value:string) => value.replaceAll("_", " ");

function State({value}:{value:string}) {
  const tone = ["ALLOW","PASS","ACTIVE","EXECUTED","SUPPORTED","CREATED"].includes(value) ? "good" : ["BLOCK","FAIL","REVOKED","REJECTED","CONTRADICTED","FAILED"].includes(value) ? "bad" : "warn";
  return <span className={`state ${tone}`}><CircleDot size={11}/>{pretty(value)}</span>;
}
function Heading({kicker,title,aside}:{kicker:string;title:string;aside?:string}) {
  return <div className="section-head"><div><p className="kicker">{kicker}</p><h2>{title}</h2></div>{aside&&<p className="section-aside">{aside}</p>}</div>;
}
function Empty({icon:Icon,title,body}:{icon:typeof Activity;title:string;body:string}) {
  return <div className="empty"><Icon size={28}/><strong>{title}</strong><p>{body}</p></div>;
}

export default function App() {
  const [view,setView] = useState<View>("overview");
  const [products,setProducts] = useState<Product[]>([]); const [audit,setAudit] = useState<AuditEvent[]>([]);
  const [mandate,setMandate] = useState<Mandate|null>(null); const [draft,setDraft] = useState<Draft|null>(null);
  const [instruction,setInstruction] = useState(defaultInstruction); const [decision,setDecision] = useState<Decision|null>(null);
  const [selected,setSelected] = useState("prod_a"); const [stepUp,setStepUp] = useState<Record<string,unknown>|null>(null);
  const [order,setOrder] = useState<{razorpay_order_id:string;status:string}|null>(null); const [busy,setBusy] = useState(""); const [error,setError] = useState("");
  const refresh = useCallback(async()=>{const [catalog,events]=await Promise.all([request<Product[]>("/api/v1/products"),request<AuditEvent[]>("/api/v1/audit?limit=100")]);setProducts(catalog);setAudit(events)},[]);
  useEffect(()=>{refresh().catch(err=>setError(err.message))},[refresh]);
  async function act(label:string,fn:()=>Promise<void>){setBusy(label);setError("");try{await fn();await refresh()}catch(err){setError(err instanceof Error?err.message:"Request failed")}finally{setBusy("")}}
  const compile=()=>act("compile",async()=>setDraft(await request<Draft>("/api/v1/mandates/compile",{method:"POST",body:JSON.stringify({instruction_text:instruction,merchant_id:"merchant_demo"})})));
  const issue=()=>draft?.hard_constraints&&act("issue",async()=>{const value=await request<Mandate>("/api/v1/mandates",{method:"POST",body:JSON.stringify({instruction_text:instruction,hard_constraints:draft.hard_constraints,semantic_constraints:draft.semantic_constraints,expires_at:new Date(Date.now()+3600000).toISOString()})});setMandate(value);setDecision(null);setOrder(null);setView("mandate")});
  const revoke=()=>mandate&&act("revoke",async()=>setMandate(await request<Mandate>(`/api/v1/mandates/${mandate.id}/revoke`,{method:"POST"})));
  const propose=()=>mandate&&act("propose",async()=>{const value=await request<{decision:Decision}>("/api/v1/proposals",{method:"POST",body:JSON.stringify({mandate_id:mandate.id,mandate_version:mandate.version,product_id:selected,quantity:1,agent_request_id:`agent-${crypto.randomUUID()}`})});setDecision(value.decision);setOrder(null);if(value.decision.step_up_id)setStepUp(await request(`/api/v1/step-ups/${value.decision.step_up_id}`))});
  const execute=()=>decision&&act("execute",async()=>setOrder(await request(`/api/v1/proposals/${decision.proposal_id}/execute`,{method:"POST"})));
  const resolve=(choice:"approve"|"reject")=>decision?.step_up_id&&act(choice,async()=>{const value=await request<Record<string,unknown>>(`/api/v1/step-ups/${decision.step_up_id}/${choice}`,{method:"POST"});setStepUp(value);if(choice==="approve")setOrder(value as {razorpay_order_id:string;status:string})});
  let content;
  if(view==="issue")content=<Issue instruction={instruction} setInstruction={setInstruction} draft={draft} compile={compile} issue={issue} busy={busy}/>;
  else if(view==="mandate")content=<MandateView mandate={mandate} revoke={revoke} busy={busy} go={()=>setView("simulator")}/>;
  else if(view==="simulator")content=<Simulator mandate={mandate} products={products} selected={selected} setSelected={setSelected} propose={propose} execute={execute} decision={decision} order={order} busy={busy} goStepUp={()=>setView("stepup")}/>;
  else if(view==="stepup")content=<StepUp decision={decision} data={stepUp} order={order} resolve={resolve} busy={busy}/>;
  else if(view==="audit")content=<Audit events={audit} refresh={()=>act("refresh",refresh)} busy={busy}/>;
  else content=<Overview products={products} events={audit} mandate={mandate} go={setView}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="mark">J</div><div><strong>JANUS</strong><span>Authorization gateway</span></div></div><nav>{nav.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><item.icon size={17}/><span>{item.label}</span>{view===item.id&&<ChevronRight size={14}/>}</button>)}</nav><div className="rail-status"><span className="pulse"/><div><strong>CONTROL PLANE ONLINE</strong><small>Razorpay · test mode only</small></div></div></aside><main className="workspace"><header className="topbar"><div><span>MERCHANT</span><strong>JANUS DEMO STORE</strong></div><div className="top-actions"><span className="mode"><LockKeyhole size={13}/> FAIL-CLOSED</span><a href="https://github.com/vivekyarra/Janus" target="_blank" rel="noreferrer">SOURCE <SquareArrowOutUpRight size={13}/></a></div></header>{error&&<div className="error-banner"><TriangleAlert size={16}/><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss"><X size={15}/></button></div>}<div className="content">{content}</div></main></div>;
}

function Overview({products,events,mandate,go}:{products:Product[];events:AuditEvent[];mandate:Mandate|null;go:(v:View)=>void}) {
  const nodes=[["01","Signed mandate","Human-reviewed authority",Fingerprint],["02","Hard gate","Exact deterministic checks",ShieldCheck],["03","Semantic evidence","Supported · contradicted · unknown",Activity],["04","Razorpay order","Reachable only after ALLOW",ShoppingBag]] as const;
  return <><Heading kicker="CONTROL ROOM / 00" title="Authority before action." aside="Every irreversible action crosses a deterministic boundary. AI interprets merchant evidence; it cannot expand authority."/><div className="thesis-flow">{nodes.map(([n,t,d,Icon],i)=><div className="flow-node" key={n}><div><span>{n}</span><Icon size={20}/></div><strong>{t}</strong><small>{d}</small>{i<3&&<ArrowRight className="flow-arrow" size={17}/>}</div>)}</div><div className="metric-grid"><article><span>CATALOG AUTHORITY</span><strong>{String(products.length).padStart(2,"0")}</strong><small>merchant-controlled products</small></article><article><span>CURRENT MANDATE</span><strong>{mandate?.status??"NONE"}</strong><small>{mandate?`version ${mandate.version} · ${mandate.execution_count}/${mandate.max_executions} used`:"issue one to begin"}</small></article><article><span>AUDIT EVENTS</span><strong>{String(events.length).padStart(2,"0")}</strong><small>structured decision records</small></article></div><div className="split"><section className="panel"><div className="panel-title"><span>DECISION CONTRACT</span><ShieldCheck size={17}/></div><div className="decision-table"><div><span>Hard FAIL</span><State value="BLOCK"/><small>Razorpay never called</small></div><div><span>PASS + supported</span><State value="ALLOW"/><small>Execution may be reserved</small></div><div><span>Contradicted / unknown</span><State value="STEP_UP"/><small>Human decides once</small></div></div></section><section className="panel next"><p className="kicker">NEXT SAFE ACTION</p><h3>{mandate?"Test the boundary":"Delegate a bounded purchase"}</h3><p>{mandate?"Send a catalog product through both authorization paths.":"Turn an instruction into reviewable hard and semantic constraints."}</p><button className="primary" onClick={()=>go(mandate?"simulator":"issue")}>{mandate?"OPEN AGENT CHECKOUT":"ISSUE MANDATE"}<ArrowRight size={16}/></button></section></div></>;
}

function Issue({instruction,setInstruction,draft,compile,issue,busy}:{instruction:string;setInstruction:(v:string)=>void;draft:Draft|null;compile:()=>void;issue:()=>void;busy:string}) {
  return <><Heading kicker="MANDATES / 01" title="Turn intent into bounded authority." aside="The compiler never invents numbers, merchants, or expiry. Review exact structure before signing."/><div className="split"><section className="panel form-panel"><label htmlFor="instruction">HUMAN INSTRUCTION</label><textarea id="instruction" value={instruction} onChange={e=>setInstruction(e.target.value)} rows={8}/><div className="form-note"><LockKeyhole size={15}/>Ambiguous money limits stay unresolved.</div><button className="primary" onClick={compile} disabled={!!busy}><Activity size={16}/>{busy==="compile"?"COMPILING…":"COMPILE AUTHORITY"}</button></section><section className="panel compiled"><div className="panel-title"><span>REVIEW BEFORE SIGNING</span>{draft&&<State value={draft.unresolved.length?"STEP_UP":"PASS"}/>}</div>{draft?<><div className="constraint-group"><label>HARD CONSTRAINTS</label>{draft.hard_constraints?Object.entries(draft.hard_constraints).map(([key,value])=><div className="constraint" key={key}><span>{pretty(key)}</span><strong>{key.includes("amount")?money(value as number):Array.isArray(value)?value.join(", "):String(value)}</strong></div>):<p className="muted">No hard authority compiled.</p>}</div><div className="constraint-group"><label>SEMANTIC CONSTRAINTS</label>{draft.semantic_constraints.map(item=><div className="semantic-line" key={item.id}><Activity size={14}/><span>{item.text}</span><small>AI evidence path</small></div>)}</div>{draft.unresolved.map(item=><div className="unresolved" key={item.field}><TriangleAlert size={15}/><div><strong>{pretty(item.field)}</strong><small>{item.reason}</small></div></div>)}<button className="primary full" onClick={issue} disabled={!draft.hard_constraints||!!draft.unresolved.length||!!busy}><Fingerprint size={16}/>{busy==="issue"?"SIGNING…":"APPROVE & SIGN MANDATE"}</button></>:<Empty icon={FileKey2} title="No compiled draft" body="Compile the instruction to inspect exact authority and unresolved fields."/>}</section></div></>;
}

function MandateView({mandate,revoke,busy,go}:{mandate:Mandate|null;revoke:()=>void;busy:string;go:()=>void}) {
  if(!mandate)return <><Heading kicker="MANDATES / 02" title="No mandate selected."/><Empty icon={Fingerprint} title="Issue a mandate first" body="Signed authority and live server state will appear here."/></>;
  return <><Heading kicker="MANDATES / 02" title="Signed authority, live state." aside="A valid signature cannot override revocation, expiry, version state, or consumption."/><div className="mandate-banner"><div><span>MANDATE ID</span><code>{mandate.id}</code></div><State value={mandate.status}/></div><div className="split"><section className="panel"><div className="panel-title"><span>HARD AUTHORITY</span><Fingerprint size={17}/></div>{Object.entries(mandate.hard_constraints).map(([key,value])=><div className="constraint" key={key}><span>{pretty(key)}</span><strong>{key.includes("amount")?money(value as number):Array.isArray(value)?value.join(", "):String(value)}</strong></div>)}</section><section className="panel"><div className="panel-title"><span>CRYPTOGRAPHIC ENVELOPE</span><ShieldCheck size={17}/></div><div className="key-row"><span>Algorithm</span><strong>ECDSA P-256 / SHA-256</strong></div><div className="key-row"><span>Version</span><strong>{mandate.version}</strong></div><div className="key-row"><span>Expires</span><strong>{when(mandate.expires_at)}</strong></div><div className="key-row"><span>Signature</span><code>{mandate.signature.slice(0,34)}…</code></div><div className="button-row"><button className="danger" onClick={revoke} disabled={mandate.status!=="ACTIVE"||!!busy}><Ban size={16}/>REVOKE</button><button className="primary" onClick={go} disabled={mandate.status!=="ACTIVE"}>TEST CHECKOUT<ArrowRight size={16}/></button></div></section></div></>;
}

function Simulator({mandate,products,selected,setSelected,propose,execute,decision,order,busy,goStepUp}:{mandate:Mandate|null;products:Product[];selected:string;setSelected:(v:string)=>void;propose:()=>void;execute:()=>void;decision:Decision|null;order:{razorpay_order_id:string;status:string}|null;busy:string;goStepUp:()=>void}) {
  return <><Heading kicker="AGENT CHECKOUT / 03" title="Propose. Verify. Then execute." aside="The buyer supplies IDs and quantity. Merchant facts resolve from the authoritative catalog."/>{!mandate?<Empty icon={ShoppingBag} title="No active authority" body="Issue a mandate before an agent can propose checkout."/>:<div className="checkout-layout"><section className="panel catalog"><div className="panel-title"><span>MERCHANT CATALOG</span><small>AUTHORITATIVE SOURCE</small></div>{products.map(product=><button className={`product-row ${selected===product.id?"selected":""}`} onClick={()=>setSelected(product.id)} key={product.id}><span className="radio">{selected===product.id&&<Check size={12}/>}</span><div><strong>{product.name}</strong><small>{product.id} · {product.category} · {product.condition}</small></div><b>{money(product.price_paise)}</b></button>)}<button className="primary full" onClick={propose} disabled={!!busy}><Play size={15}/>{busy==="propose"?"EVALUATING…":"PROPOSE CHECKOUT"}</button></section><section className="decision-stack">{decision?<DecisionCard decision={decision}/>:<div className="panel"><Empty icon={ShieldCheck} title="Awaiting proposal" body="Select a product and send it through both authorization paths."/></div>}{decision?.decision==="ALLOW"&&!order&&<button className="execute" onClick={execute} disabled={!!busy}><span><ShieldCheck size={18}/>AUTHORIZATION CLEARED<small>Reserve atomically, then call Razorpay</small></span><span>{busy==="execute"?"EXECUTING…":"CREATE TEST ORDER"}<ArrowRight size={16}/></span></button>}{decision?.decision==="STEP_UP"&&<button className="step-action" onClick={goStepUp}><span><UserCheck size={18}/>HUMAN DECISION REQUIRED</span><ArrowRight size={16}/></button>}{order&&<div className="order-proof"><Check size={20}/><div><span>RAZORPAY ORDER CREATED</span><code>{order.razorpay_order_id}</code></div><State value="EXECUTED"/></div>}</section></div>}</>;
}

function DecisionCard({decision}:{decision:Decision}) {
  return <div className="panel decision-card"><div className="decision-hero"><div><span>FINAL DECISION</span><strong>{decision.decision}</strong><small>{decision.reason_code?pretty(decision.reason_code):"All authorization paths cleared"}</small></div><State value={decision.decision}/></div><div className="path-result"><div><ShieldCheck size={16}/><span>HARD GATE</span><State value={decision.hard_gate.status}/></div><div className="checks">{decision.hard_gate.checks.map(check=><div key={check.name}><span className={check.passed?"check good":"check bad"}>{check.passed?<Check size={12}/>:<X size={12}/>}</span><span>{pretty(check.name)}</span><small>{check.source}</small></div>)}</div></div>{decision.semantic&&<div className="path-result"><div><Activity size={16}/><span>SEMANTIC PATH</span><State value={decision.semantic.service_status==="UNAVAILABLE"?"STEP_UP":decision.semantic.results[0]?.status??"SUPPORTED"}/></div>{decision.semantic.results.map(item=><div className="semantic-result" key={item.constraint_id}><strong>{pretty(item.constraint_id)}</strong><p>{item.reason}</p><small>{item.evidence.map(e=>`${e.field}: ${String(e.value)}`).join(" · ")||"No sufficient evidence"}</small></div>)}</div>}</div>;
}

function StepUp({decision,data,order,resolve,busy}:{decision:Decision|null;data:Record<string,unknown>|null;order:{razorpay_order_id:string;status:string}|null;resolve:(c:"approve"|"reject")=>void;busy:string}) {
  if(!decision?.step_up_id||!data)return <><Heading kicker="STEP-UP / 04" title="No human decision pending."/><Empty icon={UserCheck} title="The safe path is quiet" body="Contradiction, missing evidence, or model failure creates a bound step-up here."/></>;
  const status=String(data.status);return <><Heading kicker="STEP-UP / 04" title="Ambiguity belongs to a human." aside="Approve-once binds one mandate, proposal, product, and amount. It never broadens authority."/><div className="split"><section className="panel"><div className="panel-title"><span>ESCALATION</span><State value={status}/></div><div className="step-reason"><TriangleAlert size={22}/><div><span>REASON CODE</span><strong>{pretty(String(data.reason_code))}</strong></div></div><div className="key-row"><span>Proposal</span><code>{String(data.proposal_id)}</code></div><div className="key-row"><span>Binding hash</span><code>{String(data.binding_hash).slice(0,38)}…</code></div><div className="key-row"><span>Override scope</span><strong>THIS PROPOSAL ONCE</strong></div></section><section className="panel human-decision"><span>HUMAN AUTHORIZATION</span><h3>Accept this specific exception?</h3><p>The hard gate passed. This resolves semantic uncertainty only; exact monetary constraints remain unchanged.</p>{status==="PENDING"?<div className="button-row"><button className="danger" onClick={()=>resolve("reject")} disabled={!!busy}><Ban size={16}/>REJECT</button><button className="primary" onClick={()=>resolve("approve")} disabled={!!busy}><UserCheck size={16}/>APPROVE ONCE</button></div>:<State value={status}/>}</section></div>{order&&<div className="order-proof"><Check size={20}/><div><span>ONE-SHOT APPROVAL CONSUMED</span><code>{order.razorpay_order_id}</code></div><State value="EXECUTED"/></div>}</>;
}

function Audit({events,refresh,busy}:{events:AuditEvent[];refresh:()=>void;busy:string}) {
  return <><Heading kicker="AUDIT / 05" title="Every decision leaves evidence." aside="Facts, exact checks, reason codes, merchant evidence, execution state, and timestamps—never chain-of-thought."/><div className="audit-toolbar"><span>{events.length} EVENTS · NEWEST FIRST</span><button onClick={refresh}><RefreshCw className={busy==="refresh"?"spin":""} size={14}/>REFRESH</button></div><div className="audit-list">{events.map((event,index)=><details key={event.id}><summary><span className="event-index">{String(events.length-index).padStart(3,"0")}</span><span className="event-dot"/><time>{when(event.created_at)}</time><strong>{pretty(event.event_type)}</strong><code>{event.entity_id.slice(0,22)}</code><ChevronRight size={15}/></summary><pre>{JSON.stringify(event.payload,null,2)}</pre></details>)}{!events.length&&<Empty icon={Clock3} title="No events yet" body="Issue a mandate to begin the decision story."/>}</div></>;
}
