import json
from pathlib import Path

ROOT = Path("d:/janus")
cases_path = ROOT / "evals" / "semantic_cases.json"
existing_cases = json.loads(cases_path.read_text(encoding="utf-8"))

print(f"Loaded {len(existing_cases)} existing semantic cases.")

new_cases = [
    # ── Hinglish / Indian Commerce Colloquial Intent (30 cases) ──
    {
        "name": "hinglish_clear_sound_not_party_support",
        "instruction": "Bhai sound clear honi chahiye, zyada loud party type nahi",
        "constraint": {"id": "clear_sound", "text": "clear balanced sound not boomy party bass"},
        "evidence": {"sound_signature": "balanced_vocal_clarity", "thd_percent": 0.05, "bass_boost": False},
        "model": {"status": "SUPPORTED", "fields": ["sound_signature", "bass_boost"], "confidence": 0.96},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_clear_sound_not_party_contradiction",
        "instruction": "Bhai sound clear honi chahiye, zyada loud party type nahi",
        "constraint": {"id": "clear_sound", "text": "clear balanced sound not boomy party bass"},
        "evidence": {"sound_signature": "extreme_club_bass_boost", "bass_boost": True, "clarity_rating": "low"},
        "model": {"status": "CONTRADICTED", "fields": ["sound_signature", "bass_boost"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_no_chamak_dhamak_support",
        "instruction": "Formal office meetings ke liye decent look, chamak-dhamak bilkul nahi",
        "constraint": {"id": "no_chamak_dhamak", "text": "decent corporate look no flashy bling"},
        "evidence": {"color": "matte_slate", "finish": "non_reflective", "lighting": "none"},
        "model": {"status": "SUPPORTED", "fields": ["color", "finish", "lighting"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_no_chamak_dhamak_contradiction",
        "instruction": "Formal office meetings ke liye decent look, chamak-dhamak bilkul nahi",
        "constraint": {"id": "no_chamak_dhamak", "text": "decent corporate look no flashy bling"},
        "evidence": {"color": "glitter_gold", "finish": "mirror_chrome", "rgb_lights": "pulsing_neon"},
        "model": {"status": "CONTRADICTED", "fields": ["color", "finish", "rgb_lights"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_travel_compact_bag_support",
        "instruction": "Travel me carry karne layak compact cheez chahiye, bag me fit ho jaye",
        "constraint": {"id": "travel_compact", "text": "compact foldable for bag carry"},
        "evidence": {"foldable": True, "case_type": "flat_slipcase", "weight_g": 210},
        "model": {"status": "SUPPORTED", "fields": ["foldable", "weight_g"], "confidence": 0.95},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_travel_compact_bag_contradiction",
        "instruction": "Travel me carry karne layak compact cheez chahiye, bag me fit ho jaye",
        "constraint": {"id": "travel_compact", "text": "compact foldable for bag carry"},
        "evidence": {"foldable": False, "form_factor": "fixed_studio_bracket", "dimensions_cm": "35x30x18"},
        "model": {"status": "CONTRADICTED", "fields": ["foldable", "form_factor"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_rough_use_commute_support",
        "instruction": "Rough use ke liye solid build quality, daily commute me tut na jaye",
        "constraint": {"id": "solid_build", "text": "rugged durable build for daily rough commute"},
        "evidence": {"material": "reinforced_polycarbonate_steel", "drop_tested_m": 2.0, "warranty_years": 2},
        "model": {"status": "SUPPORTED", "fields": ["material", "drop_tested_m"], "confidence": 0.94},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_rough_use_commute_contradiction",
        "instruction": "Rough use ke liye solid build quality, daily commute me tut na jaye",
        "constraint": {"id": "solid_build", "text": "rugged durable build for daily rough commute"},
        "evidence": {"material": "fragile_acrylic", "hinge": "brittle_plastic", "durability": "delicate"},
        "model": {"status": "CONTRADICTED", "fields": ["material", "hinge"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_no_cheap_plastic_feel_support",
        "instruction": "Budget friendly but sasti plastic feeling nahi aani chahiye",
        "constraint": {"id": "premium_touch", "text": "good tactile quality not cheap hollow plastic"},
        "evidence": {"chassis_finish": "soft_touch_matte", "headband": "aluminum_core", "rattle_free": True},
        "model": {"status": "SUPPORTED", "fields": ["chassis_finish", "headband"], "confidence": 0.93},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_no_cheap_plastic_feel_contradiction",
        "instruction": "Budget friendly but sasti plastic feeling nahi aani chahiye",
        "constraint": {"id": "premium_touch", "text": "good tactile quality not cheap hollow plastic"},
        "evidence": {"chassis_finish": "creaky_thin_plastic", "build": "hollow_unpadded"},
        "model": {"status": "CONTRADICTED", "fields": ["chassis_finish", "build"], "confidence": 0.96},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_gym_pasina_sweatproof_support",
        "instruction": "Gym and running me girna nahi chahiye, pasine se kharab na ho",
        "constraint": {"id": "sweat_gym", "text": "sweatproof and stable for gym and running"},
        "evidence": {"ip_rating": "IPX6", "fit_mechanism": "ear_fin_lock", "sweatproof": True},
        "model": {"status": "SUPPORTED", "fields": ["ip_rating", "sweatproof", "fit_mechanism"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_gym_pasina_sweatproof_contradiction",
        "instruction": "Gym and running me girna nahi chahiye, pasine se kharab na ho",
        "constraint": {"id": "sweat_gym", "text": "sweatproof and stable for gym and running"},
        "evidence": {"ip_rating": "IPX0_none", "fit_mechanism": "loose_resting", "water_resistance": False},
        "model": {"status": "CONTRADICTED", "fields": ["ip_rating", "water_resistance"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_battery_solid_support",
        "instruction": "Battery ekdum solid honi chahiye, roz roz charge ka jhanjhat nahi chahiye",
        "constraint": {"id": "long_battery", "text": "long battery life without frequent recharging"},
        "evidence": {"playback_hours": 50, "fast_charge_mins": 10, "battery_type": "high_density_li_ion"},
        "model": {"status": "SUPPORTED", "fields": ["playback_hours"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_battery_solid_contradiction",
        "instruction": "Battery ekdum solid honi chahiye, roz roz charge ka jhanjhat nahi chahiye",
        "constraint": {"id": "long_battery", "text": "long battery life without frequent recharging"},
        "evidence": {"playback_hours": 4, "charging_time_hours": 3.5},
        "model": {"status": "CONTRADICTED", "fields": ["playback_hours"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_mic_saaf_client_call_support",
        "instruction": "Mic ekdum saaf honi chahiye client call ke liye, background shor na jaye",
        "constraint": {"id": "clear_mic", "text": "clear noise cancelling mic for client calls"},
        "evidence": {"mic_system": "quad_ai_beamforming", "background_noise_suppression_db": 32, "certifications": ["Zoom_Certified"]},
        "model": {"status": "SUPPORTED", "fields": ["mic_system", "background_noise_suppression_db"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_mic_saaf_client_call_contradiction",
        "instruction": "Mic ekdum saaf honi chahiye client call ke liye, background shor na jaye",
        "constraint": {"id": "clear_mic", "text": "clear noise cancelling mic for client calls"},
        "evidence": {"mic_system": "omnidirectional_unfiltered", "background_noise_suppression_db": 0},
        "model": {"status": "CONTRADICTED", "fields": ["mic_system", "background_noise_suppression_db"], "confidence": 0.96},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_balanced_classical_support",
        "instruction": "Bass bohot zyada nahi chahiye, classical aur podcast sunne ke liye balanced sound",
        "constraint": {"id": "classical_podcast", "text": "natural neutral sound for podcast and classical"},
        "evidence": {"sound_curve": "harman_neutral_target", "sub_bass_emphasis": "flat", "mids_clarity": "exceptional"},
        "model": {"status": "SUPPORTED", "fields": ["sound_curve", "mids_clarity"], "confidence": 0.96},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_balanced_classical_contradiction",
        "instruction": "Bass bohot zyada nahi chahiye, classical aur podcast sunne ke liye balanced sound",
        "constraint": {"id": "classical_podcast", "text": "natural neutral sound for podcast and classical"},
        "evidence": {"sound_curve": "bass_heavy_edm", "sub_bass_emphasis": "+12dB_boost", "vocal_clarity": "muffled"},
        "model": {"status": "CONTRADICTED", "fields": ["sound_curve", "sub_bass_emphasis"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_tv_comfort_lightweight_support",
        "instruction": "Ghar pe aaram se TV dekhne ke liye comfortable lightweight headphones",
        "constraint": {"id": "tv_comfort", "text": "comfortable lightweight for television watching"},
        "evidence": {"weight_g": 185, "low_latency_aptx": True, "earpads": "velour_open_air"},
        "model": {"status": "SUPPORTED", "fields": ["weight_g", "earpads"], "confidence": 0.95},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_tv_comfort_lightweight_contradiction",
        "instruction": "Ghar pe aaram se TV dekhne ke liye comfortable lightweight headphones",
        "constraint": {"id": "tv_comfort", "text": "comfortable lightweight for television watching"},
        "evidence": {"weight_g": 590, "audio_delay_ms": 450, "clamping_force": "heavy_pressure"},
        "model": {"status": "CONTRADICTED", "fields": ["weight_g", "clamping_force"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_flight_noise_anc_support",
        "instruction": "Flight me engine ka shor rokne ke liye mast noise cancelling chahiye",
        "constraint": {"id": "flight_anc", "text": "strong active noise cancelling for flight engine rumble"},
        "evidence": {"anc_type": "adaptive_hybrid_anc", "low_freq_attenuation_db": 38, "airplane_adapter": True},
        "model": {"status": "SUPPORTED", "fields": ["anc_type", "low_freq_attenuation_db"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_flight_noise_anc_contradiction",
        "instruction": "Flight me engine ka shor rokne ke liye mast noise cancelling chahiye",
        "constraint": {"id": "flight_anc", "text": "strong active noise cancelling for flight engine rumble"},
        "evidence": {"anc_type": "none_passive_only", "acoustic_seal": "open_back_grill"},
        "model": {"status": "CONTRADICTED", "fields": ["anc_type", "acoustic_seal"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_multipoint_seamless_support",
        "instruction": "Laptop aur phone dono se ek saath connect hona chahiye bina disconnect kiye",
        "constraint": {"id": "multipoint", "text": "seamless multipoint connection between laptop and phone"},
        "evidence": {"multipoint_pairing": True, "max_paired_devices": 2, "auto_audio_switch": True},
        "model": {"status": "SUPPORTED", "fields": ["multipoint_pairing", "auto_audio_switch"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_multipoint_seamless_contradiction",
        "instruction": "Laptop aur phone dono se ek saath connect hona chahiye bina disconnect kiye",
        "constraint": {"id": "multipoint", "text": "seamless multipoint connection between laptop and phone"},
        "evidence": {"multipoint_pairing": False, "bluetooth_profile": "single_host_only"},
        "model": {"status": "CONTRADICTED", "fields": ["multipoint_pairing"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_kano_pe_dard_soft_support",
        "instruction": "Kano pe dard na ho lambe zoom calls me, soft cushions hone chahiye",
        "constraint": {"id": "ear_comfort", "text": "no ear fatigue soft cushions for long meetings"},
        "evidence": {"earpad_cushion": "protein_leather_memory_foam", "contact_pressure_kpa": 1.2, "hours_rated": 10},
        "model": {"status": "SUPPORTED", "fields": ["earpad_cushion", "contact_pressure_kpa"], "confidence": 0.95},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_kano_pe_dard_soft_contradiction",
        "instruction": "Kano pe dard na ho lambe zoom calls me, soft cushions hone chahiye",
        "constraint": {"id": "ear_comfort", "text": "no ear fatigue soft cushions for long meetings"},
        "evidence": {"earpad_cushion": "hard_unpadded_rubber", "contact_pressure_kpa": 4.8},
        "model": {"status": "CONTRADICTED", "fields": ["earpad_cushion", "contact_pressure_kpa"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_baarish_walk_waterproof_support",
        "instruction": "Waterproof hona chahiye baarish me walk karte time tension na ho",
        "constraint": {"id": "rain_protection", "text": "waterproof for rain walks"},
        "evidence": {"waterproof_rating": "IPX7_submersible", "sealed_gaskets": True},
        "model": {"status": "SUPPORTED", "fields": ["waterproof_rating"], "confidence": 0.99},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_baarish_walk_waterproof_contradiction",
        "instruction": "Waterproof hona chahiye baarish me walk karte time tension na ho",
        "constraint": {"id": "rain_protection", "text": "waterproof for rain walks"},
        "evidence": {"waterproof_rating": "not_water_resistant", "water_damage_covered": False},
        "model": {"status": "CONTRADICTED", "fields": ["waterproof_rating"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "hinglish_durable_long_battery_support",
        "instruction": "Durable wire hona chahiye ya wireless with long battery",
        "constraint": {"id": "durable_power", "text": "durable cable or long battery wireless"},
        "evidence": {"connectivity": "wireless", "battery_hours": 45, "braided_backup_cable": True},
        "model": {"status": "SUPPORTED", "fields": ["connectivity", "battery_hours", "braided_backup_cable"], "confidence": 0.96},
        "expected": "ALLOW",
    },
    {
        "name": "hinglish_durable_long_battery_contradiction",
        "instruction": "Durable wire hona chahiye ya wireless with long battery",
        "constraint": {"id": "durable_power", "text": "durable cable or long battery wireless"},
        "evidence": {"connectivity": "wired", "cable_material": "thin_tangle_prone_pvc", "reinforced": False},
        "model": {"status": "CONTRADICTED", "fields": ["cable_material", "reinforced"], "confidence": 0.95},
        "expected": "STEP_UP",
    },

    # ── Subtle Nuanced Linguistic Preferences (25 cases) ──
    {
        "name": "subtle_understated_luxury_support",
        "instruction": "Understated luxury aesthetic",
        "constraint": {"id": "luxury", "text": "understated luxury aesthetic"},
        "evidence": {"materials": "machined_magnesium_fullgrain_leather", "branding": "debossed_interior_only", "finish": "matte_obsidian"},
        "model": {"status": "SUPPORTED", "fields": ["materials", "branding", "finish"], "confidence": 0.96},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_understated_luxury_contradiction",
        "instruction": "Understated luxury aesthetic",
        "constraint": {"id": "luxury", "text": "understated luxury aesthetic"},
        "evidence": {"materials": "cheap_hollow_abs", "branding": "rhinestone_oversized_logo", "color": "hot_pink"},
        "model": {"status": "CONTRADICTED", "fields": ["materials", "branding"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_marathon_endurance_support",
        "instruction": "Marathon battery endurance for multi-day trekking",
        "constraint": {"id": "battery_endurance", "text": "marathon multi-day battery life"},
        "evidence": {"battery_hours": 65, "solar_recharge": True, "standby_days": 180},
        "model": {"status": "SUPPORTED", "fields": ["battery_hours", "solar_recharge"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_marathon_endurance_contradiction",
        "instruction": "Marathon battery endurance for multi-day trekking",
        "constraint": {"id": "battery_endurance", "text": "marathon multi-day battery life"},
        "evidence": {"battery_hours": 5, "solar_recharge": False},
        "model": {"status": "CONTRADICTED", "fields": ["battery_hours"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_audiophile_flat_support",
        "instruction": "Strict flat reference response for acoustic mixing",
        "constraint": {"id": "reference_curve", "text": "strict flat frequency response for mixing"},
        "evidence": {"frequency_response": "20Hz-20kHz_within_1dB", "tuning": "diffuse_field_flat", "dsp_coloring": "disabled"},
        "model": {"status": "SUPPORTED", "fields": ["frequency_response", "tuning"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_audiophile_flat_contradiction",
        "instruction": "Strict flat reference response for acoustic mixing",
        "constraint": {"id": "reference_curve", "text": "strict flat frequency response for mixing"},
        "evidence": {"frequency_response": "v_shaped_scooped_mids", "tuning": "heavy_bass_hype", "dsp_coloring": "always_on"},
        "model": {"status": "CONTRADICTED", "fields": ["frequency_response", "tuning"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_zero_clamping_support",
        "instruction": "Zero skull clamping fatigue for 12-hour coding sprints",
        "constraint": {"id": "low_clamping", "text": "ultra low clamping pressure for long sessions"},
        "evidence": {"clamping_force_newtons": 2.1, "headband_type": "self_adjusting_suspension_mesh"},
        "model": {"status": "SUPPORTED", "fields": ["clamping_force_newtons", "headband_type"], "confidence": 0.95},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_zero_clamping_contradiction",
        "instruction": "Zero skull clamping fatigue for 12-hour coding sprints",
        "constraint": {"id": "low_clamping", "text": "ultra low clamping pressure for long sessions"},
        "evidence": {"clamping_force_newtons": 6.8, "headband_type": "rigid_steel_pinch"},
        "model": {"status": "CONTRADICTED", "fields": ["clamping_force_newtons", "headband_type"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_breathable_thermal_support",
        "instruction": "Breathable thermal comfort for humid Indian summers",
        "constraint": {"id": "thermal_comfort", "text": "breathable cushions that prevent heat buildup"},
        "evidence": {"earpad_technology": "mesh_cooling_gel_infused", "sweat_ventilation": True},
        "model": {"status": "SUPPORTED", "fields": ["earpad_technology", "sweat_ventilation"], "confidence": 0.96},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_breathable_thermal_contradiction",
        "instruction": "Breathable thermal comfort for humid Indian summers",
        "constraint": {"id": "thermal_comfort", "text": "breathable cushions that prevent heat buildup"},
        "evidence": {"earpad_technology": "sealed_non_porous_vinyl", "sweat_ventilation": False},
        "model": {"status": "CONTRADICTED", "fields": ["earpad_technology", "sweat_ventilation"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_fast_device_switch_support",
        "instruction": "Instant device switching between Mac and iPad",
        "constraint": {"id": "fast_switch", "text": "instant device handoff between devices"},
        "evidence": {"bluetooth_codecs": ["AAC", "LDAC"], "seamless_handoff": True, "switch_latency_ms": 120},
        "model": {"status": "SUPPORTED", "fields": ["seamless_handoff", "switch_latency_ms"], "confidence": 0.94},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_fast_device_switch_contradiction",
        "instruction": "Instant device switching between Mac and iPad",
        "constraint": {"id": "fast_switch", "text": "instant device handoff between devices"},
        "evidence": {"seamless_handoff": False, "manual_re_pairing_required": True},
        "model": {"status": "CONTRADICTED", "fields": ["seamless_handoff"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_foldable_flat_support",
        "instruction": "Swivels 180 degrees to lay completely flat on chest",
        "constraint": {"id": "lay_flat", "text": "swivels flat on collarbones"},
        "evidence": {"swivel_range_deg": 180, "flat_fold": True},
        "model": {"status": "SUPPORTED", "fields": ["swivel_range_deg", "flat_fold"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_foldable_flat_contradiction",
        "instruction": "Swivels 180 degrees to lay completely flat on chest",
        "constraint": {"id": "lay_flat", "text": "swivels flat on collarbones"},
        "evidence": {"swivel_range_deg": 0, "fixed_bracket": True},
        "model": {"status": "CONTRADICTED", "fields": ["swivel_range_deg"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_speech_transparency_support",
        "instruction": "Natural sidetone so I don't shout during phone calls",
        "constraint": {"id": "sidetone", "text": "natural sidetone voice feedback"},
        "evidence": {"voice_sidetone": True, "adjustable_sidetone_levels": 3},
        "model": {"status": "SUPPORTED", "fields": ["voice_sidetone"], "confidence": 0.95},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_speech_transparency_contradiction",
        "instruction": "Natural sidetone so I don't shout during phone calls",
        "constraint": {"id": "sidetone", "text": "natural sidetone voice feedback"},
        "evidence": {"voice_sidetone": False, "call_isolation": "total_occlusion"},
        "model": {"status": "CONTRADICTED", "fields": ["voice_sidetone"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_sustainable_recycled_support",
        "instruction": "Eco-friendly sustainable materials with zero animal leather",
        "constraint": {"id": "sustainable", "text": "eco friendly recycled materials vegan leather"},
        "evidence": {"recycled_aluminum_percent": 85, "cushions": "plant_based_vegan_leather", "plastic_free_packaging": True},
        "model": {"status": "SUPPORTED", "fields": ["recycled_aluminum_percent", "cushions"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_sustainable_recycled_contradiction",
        "instruction": "Eco-friendly sustainable materials with zero animal leather",
        "constraint": {"id": "sustainable", "text": "eco friendly recycled materials vegan leather"},
        "evidence": {"headband_wrap": "genuine_calfskin_leather", "recycled_content": 0},
        "model": {"status": "CONTRADICTED", "fields": ["headband_wrap", "recycled_content"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_subway_isolation_support",
        "instruction": "Deep acoustic isolation for chaotic city subway transit",
        "constraint": {"id": "subway_isolation", "text": "heavy acoustic isolation for subway transit"},
        "evidence": {"passive_isolation_db": 28, "active_noise_reduction_db": 35, "wind_reduction": True},
        "model": {"status": "SUPPORTED", "fields": ["passive_isolation_db", "active_noise_reduction_db"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_subway_isolation_contradiction",
        "instruction": "Deep acoustic isolation for chaotic city subway transit",
        "constraint": {"id": "subway_isolation", "text": "heavy acoustic isolation for subway transit"},
        "evidence": {"design": "open_back_diffuse", "sound_leakage": "high", "anc": False},
        "model": {"status": "CONTRADICTED", "fields": ["design", "sound_leakage"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_lossless_codec_support",
        "instruction": "High resolution lossless audio codec support",
        "constraint": {"id": "hires_audio", "text": "hires lossless codec support"},
        "evidence": {"supported_codecs": ["LDAC", "aptX_Lossless", "LHDC"], "hi_res_certified": True},
        "model": {"status": "SUPPORTED", "fields": ["supported_codecs", "hi_res_certified"], "confidence": 0.98},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_lossless_codec_contradiction",
        "instruction": "High resolution lossless audio codec support",
        "constraint": {"id": "hires_audio", "text": "hires lossless codec support"},
        "evidence": {"supported_codecs": ["SBC_only"], "bitrate_limit_kbps": 320, "hi_res_certified": False},
        "model": {"status": "CONTRADICTED", "fields": ["supported_codecs"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_tactile_dial_support",
        "instruction": "Smooth rotary physical volume dial like luxury audio gear",
        "constraint": {"id": "rotary_dial", "text": "rotary volume knob physical control"},
        "evidence": {"volume_control": "aluminum_knurled_rotary_dial", "haptic_clicks": True},
        "model": {"status": "SUPPORTED", "fields": ["volume_control"], "confidence": 0.97},
        "expected": "ALLOW",
    },
    {
        "name": "subtle_tactile_dial_contradiction",
        "instruction": "Smooth rotary physical volume dial like luxury audio gear",
        "constraint": {"id": "rotary_dial", "text": "rotary volume knob physical control"},
        "evidence": {"volume_control": "touchpad_swipe_gesture_only", "knurled_dial": False},
        "model": {"status": "CONTRADICTED", "fields": ["volume_control"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "subtle_aerospace_titanium_support",
        "instruction": "Lightweight titanium construction that will outlast years of use",
        "constraint": {"id": "titanium_build", "text": "titanium frame construction"},
        "evidence": {"frame_alloy": "grade_5_titanium", "tensile_strength_mpa": 950},
        "model": {"status": "SUPPORTED", "fields": ["frame_alloy"], "confidence": 0.99},
        "expected": "ALLOW",
    },

    # ── Conflicting Merchant Evidence (Marketing fluff vs Reality) (20 cases) ──
    {
        "name": "conflict_travel_claim_vs_weight_contradiction",
        "instruction": "Lightweight travel headphones",
        "constraint": {"id": "travel_weight", "text": "lightweight for travel"},
        "evidence": {"marketing_headline": "Ultimate Ultraportable Nomad Traveler", "weight_g": 940, "foldable": False},
        "model": {"status": "CONTRADICTED", "fields": ["weight_g", "foldable"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_waterproof_claim_vs_spec_contradiction",
        "instruction": "Waterproof for rainy outdoor cycling",
        "constraint": {"id": "waterproof", "text": "waterproof for rainy cycling"},
        "evidence": {"marketing_tagline": "Built For The Elements", "ip_rating": "IPX0_no_water_protection"},
        "model": {"status": "CONTRADICTED", "fields": ["ip_rating"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_office_zoom_claim_vs_no_mic_contradiction",
        "instruction": "Headset with microphone for professional office meetings",
        "constraint": {"id": "office_mic", "text": "headset with mic for meetings"},
        "evidence": {"marketing_pitch": "Perfect for Remote Work & Collaboration", "microphone": "none_headphone_only"},
        "model": {"status": "CONTRADICTED", "fields": ["microphone"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_anc_claim_vs_passive_spec_contradiction",
        "instruction": "Active noise cancelling for airplane cabin hum",
        "constraint": {"id": "anc", "text": "active noise cancelling for flights"},
        "evidence": {"marketing_name": "Pro Noise Shield Edition", "anc_circuit": "none_passive_earcup_damping_only"},
        "model": {"status": "CONTRADICTED", "fields": ["anc_circuit"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_battery_endurance_claim_vs_spec_contradiction",
        "instruction": "Long battery life for weekend trips without charger",
        "constraint": {"id": "battery_weekend", "text": "long battery life for weekend without charger"},
        "evidence": {"marketing_blurb": "Endless Sound All Day Long", "battery_hours": 3.5},
        "model": {"status": "CONTRADICTED", "fields": ["battery_hours"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_wireless_claim_vs_spec_contradiction",
        "instruction": "Wireless freedom for walking around apartment",
        "constraint": {"id": "wireless", "text": "wireless bluetooth connection"},
        "evidence": {"marketing_copy": "Wireless Style & Freedom", "connection_type": "wired_3_5mm_only"},
        "model": {"status": "CONTRADICTED", "fields": ["connection_type"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_flat_fold_claim_vs_spec_contradiction",
        "instruction": "Folds flat to slip into laptop backpack sleeve",
        "constraint": {"id": "flat_fold", "text": "folds flat for laptop bag"},
        "evidence": {"marketing_slogan": "Go Anywhere Pack Friendly", "foldable": False, "structure": "rigid_cage"},
        "model": {"status": "CONTRADICTED", "fields": ["foldable", "structure"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_audiophile_claim_vs_high_distortion_contradiction",
        "instruction": "Pristine audiophile clarity with low harmonic distortion",
        "constraint": {"id": "low_distortion", "text": "audiophile low distortion"},
        "evidence": {"marketing_label": "Audiophile Master Reference Gold", "thd_distortion_percent": 8.5},
        "model": {"status": "CONTRADICTED", "fields": ["thd_distortion_percent"], "confidence": 0.97},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_running_claim_vs_loose_fit_contradiction",
        "instruction": "Secure fit that will not fly off during sprints",
        "constraint": {"id": "secure_fit", "text": "secure fit for sprints"},
        "evidence": {"marketing_title": "Speed Athlete Edition", "ear_fit": "loose_resting_pad", "sports_clamping": False},
        "model": {"status": "CONTRADICTED", "fields": ["ear_fit", "sports_clamping"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_usbc_claim_vs_microusb_spec_contradiction",
        "instruction": "Must charge via modern USB Type C cable",
        "constraint": {"id": "usbc", "text": "usb c charging port"},
        "evidence": {"marketing_text": "Universal Modern Fast Charging", "charging_jack": "micro_usb_type_b"},
        "model": {"status": "CONTRADICTED", "fields": ["charging_jack"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_leather_claim_vs_plastic_spec_contradiction",
        "instruction": "Genuine leather cushions for premium tactile feel",
        "constraint": {"id": "genuine_leather", "text": "genuine leather cushions"},
        "evidence": {"marketing_badge": "Handcrafted Leather Elegance", "cushion_substance": "100_percent_pvc_plastic"},
        "model": {"status": "CONTRADICTED", "fields": ["cushion_substance"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_bass_minimal_claim_vs_boomy_spec_contradiction",
        "instruction": "Delicate acoustic mids without overwhelming bass boom",
        "constraint": {"id": "tamed_bass", "text": "delicate mids without heavy bass boom"},
        "evidence": {"marketing_phrase": "Acoustic Vocal Paradise", "bass_boost_db": 18, "sub_woofer_mode": "always_active"},
        "model": {"status": "CONTRADICTED", "fields": ["bass_boost_db", "sub_woofer_mode"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_discrete_claim_vs_glowing_logo_contradiction",
        "instruction": "Subtle discreet appearance with no luminescent badges",
        "constraint": {"id": "no_glow", "text": "discreet no luminescent badges"},
        "evidence": {"marketing_blurb": "Stealth Executive Understated", "earcup_illumination": "fluorescent_green_led"},
        "model": {"status": "CONTRADICTED", "fields": ["earcup_illumination"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_case_included_claim_vs_spec_contradiction",
        "instruction": "Must include protective travel case in retail packaging",
        "constraint": {"id": "case_in_box", "text": "includes protective travel case in box"},
        "evidence": {"marketing_claim": "Travel Bundle Ready", "box_contents": ["headset", "charging_wire"], "case_sold_separately": True},
        "model": {"status": "CONTRADICTED", "fields": ["box_contents", "case_sold_separately"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_multipoint_claim_vs_spec_contradiction",
        "instruction": "Simultaneous connection to phone and work computer",
        "constraint": {"id": "dual_connect", "text": "simultaneous dual device connection"},
        "evidence": {"marketing_feature": "Connect All Your Life", "simultaneous_device_links": 1},
        "model": {"status": "CONTRADICTED", "fields": ["simultaneous_device_links"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_metal_hinge_claim_vs_spec_contradiction",
        "instruction": "Reinforced steel hinges for durability",
        "constraint": {"id": "steel_hinge", "text": "steel reinforced hinges"},
        "evidence": {"marketing_header": "Heavy Duty Steel Reinforced", "hinge_joint": "thin_injection_molded_plastic"},
        "model": {"status": "CONTRADICTED", "fields": ["hinge_joint"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_noise_reduction_mic_claim_vs_spec_contradiction",
        "instruction": "Microphone must eliminate street traffic noise",
        "constraint": {"id": "traffic_mic", "text": "mic eliminates street traffic noise"},
        "evidence": {"marketing_copy": "Talk Anywhere Even in Traffic", "mic_noise_cancellation": "none_raw_analog"},
        "model": {"status": "CONTRADICTED", "fields": ["mic_noise_cancellation"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_featherlight_claim_vs_spec_contradiction",
        "instruction": "Featherlight design under 200 grams",
        "constraint": {"id": "under_200g", "text": "featherlight under 200g"},
        "evidence": {"marketing_headline": "Weightless Feather Cloud", "net_weight_g": 485},
        "model": {"status": "CONTRADICTED", "fields": ["net_weight_g"], "confidence": 0.99},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_transparency_claim_vs_spec_contradiction",
        "instruction": "Must have transparency pass-through mode for street awareness",
        "constraint": {"id": "pass_through", "text": "transparency mode for street awareness"},
        "evidence": {"marketing_line": "Hear The World Around You", "transparency_mic_passthrough": False},
        "model": {"status": "CONTRADICTED", "fields": ["transparency_mic_passthrough"], "confidence": 0.98},
        "expected": "STEP_UP",
    },
    {
        "name": "conflict_wireless_charging_claim_vs_spec_contradiction",
        "instruction": "Support for wireless charging pads",
        "constraint": {"id": "pad_charge", "text": "support for wireless charging pads"},
        "evidence": {"marketing_pitch": "Cable Free Lifestyle", "induction_charging": False, "plug_in_required": True},
        "model": {"status": "CONTRADICTED", "fields": ["induction_charging"], "confidence": 0.99},
        "expected": "STEP_UP",
    },

    # ── Ambiguous Queries with Incomplete/Missing Catalog Evidence (15 cases) ──
    {
        "name": "ambiguous_meditation_suitability",
        "instruction": "Suitable for guided deep meditation sessions",
        "constraint": {"id": "meditation", "text": "suitable for guided meditation"},
        "evidence": {"weight_g": 230, "color": "black", "bluetooth": "5.2"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["weight_g"], "confidence": 0.40},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_asmr_binaural_evidence",
        "instruction": "Optimized for 3D binaural ASMR whispers",
        "constraint": {"id": "asmr", "text": "optimized for binaural asmr"},
        "evidence": {"impedance_ohms": 32, "wireless": True},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["impedance_ohms"], "confidence": 0.35},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_good_vibe_evidence",
        "instruction": "Has an upbeat artistic design vibe",
        "constraint": {"id": "vibe", "text": "upbeat artistic design vibe"},
        "evidence": {"chassis_dimensions": "20x18x8", "battery_mah": 500},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.20},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_sleep_pillow_evidence",
        "instruction": "Comfortable for sleeping on my side against a firm pillow",
        "constraint": {"id": "side_sleeping", "text": "comfortable for sleeping on side against pillow"},
        "evidence": {"driver_size_mm": 40, "color": "white"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.30},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_podcast_host_voice_evidence",
        "instruction": "Tuned to make baritone podcast voices sound resonant",
        "constraint": {"id": "baritone_voice", "text": "resonant tuning for baritone voice"},
        "evidence": {"cable_length_m": 1.2, "plug": "gold_plated"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.25},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_glasses_temple_pressure_evidence",
        "instruction": "Will not press painfully against thick eyeglasses frames",
        "constraint": {"id": "glasses_wearer", "text": "comfort for thick eyeglasses frames"},
        "evidence": {"bluetooth_version": "5.3", "standby_hours": 100},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.40},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_vintage_classic_aura_evidence",
        "instruction": "Evokes a 1970s analog jazz cafe nostalgia",
        "constraint": {"id": "vintage_aura", "text": "1970s analog jazz nostalgia"},
        "evidence": {"weight_g": 310, "impedance": 60},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.15},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_child_safe_decibel_evidence",
        "instruction": "Volume limited to safe decibels for a 10 year old child",
        "constraint": {"id": "child_safe", "text": "volume limited decibels for children"},
        "evidence": {"color": "bright_blue", "wireless": True},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["color"], "confidence": 0.30},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_cycling_wind_mic_evidence",
        "instruction": "Wind-resistant microphones that work while biking at 25 km/h",
        "constraint": {"id": "wind_bike_mic", "text": "mic works in 25kmh cycling wind"},
        "evidence": {"mic_present": True, "bluetooth": "5.0"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["mic_present"], "confidence": 0.45},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_dog_walking_awareness_evidence",
        "instruction": "Allows hearing approaching vehicles while walking dogs in dusk",
        "constraint": {"id": "dog_walk_safety", "text": "awareness of approaching vehicles"},
        "evidence": {"case_color": "charcoal", "usb_c": True},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": [], "confidence": 0.20},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_airplane_two_prong_evidence",
        "instruction": "Compatible with twin-prong airline audio jack systems",
        "constraint": {"id": "airline_twin_prong", "text": "twin prong airline adapter included"},
        "evidence": {"anc": True, "case": True},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["case"], "confidence": 0.50},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_extreme_cold_subzero_evidence",
        "instruction": "Battery maintains voltage in -20C Himalayan winter conditions",
        "constraint": {"id": "subzero_battery", "text": "operates in minus 20C winter conditions"},
        "evidence": {"battery_hours": 30, "weight_g": 260},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["battery_hours"], "confidence": 0.35},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_fast_swimming_lap_evidence",
        "instruction": "Can be submerged while swimming pool laps",
        "constraint": {"id": "swimming_laps", "text": "submerged swimming laps use"},
        "evidence": {"fit": "wrap_around", "color": "teal"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["fit"], "confidence": 0.25},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_dj_cue_auditioning_evidence",
        "instruction": "One ear flip style for club DJ cue monitoring",
        "constraint": {"id": "dj_cue_monitoring", "text": "one ear flip for dj cueing"},
        "evidence": {"max_volume_db": 105, "coiled_cable": True},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["coiled_cable"], "confidence": 0.45},
        "expected": "STEP_UP",
    },
    {
        "name": "ambiguous_gaming_footstep_imaging_evidence",
        "instruction": "Pinpoint spatial audio imaging for enemy footsteps in CS:GO",
        "constraint": {"id": "footstep_imaging", "text": "pinpoint spatial imaging for enemy footsteps"},
        "evidence": {"channels": "stereo", "drivers": "dynamic_40mm"},
        "model": {"status": "INSUFFICIENT_EVIDENCE", "fields": ["channels"], "confidence": 0.40},
        "expected": "STEP_UP",
    },

    # ── Calibrated Confidence Threshold Abstention Tests (10 cases) ──
    # Model marks SUPPORTED, but confidence is below 0.85 -> System abstains to STEP_UP!
    {
        "name": "calibrated_abstain_office_low_confidence",
        "instruction": "Executive call headset",
        "constraint": {"id": "exec_call", "text": "executive headset for client calls"},
        "evidence": {"mic_present": True, "wireless": True},
        "model": {"status": "SUPPORTED", "fields": ["mic_present"], "confidence": 0.62},
        "expected": "STEP_UP",  # Calibrated abstention: 0.62 < 0.85 -> fails closed to Step-Up!
    },
    {
        "name": "calibrated_abstain_travel_low_confidence",
        "instruction": "Compact travel headphones",
        "constraint": {"id": "travel", "text": "compact travel headphones"},
        "evidence": {"weight_g": 290},
        "model": {"status": "SUPPORTED", "fields": ["weight_g"], "confidence": 0.70},
        "expected": "STEP_UP",  # 0.70 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_durability_low_confidence",
        "instruction": "Durable build quality",
        "constraint": {"id": "durable", "text": "durable build quality"},
        "evidence": {"weight_g": 320},
        "model": {"status": "SUPPORTED", "fields": ["weight_g"], "confidence": 0.55},
        "expected": "STEP_UP",  # 0.55 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_gym_low_confidence",
        "instruction": "Gym-ready headphones",
        "constraint": {"id": "gym_ready", "text": "gym ready headphones"},
        "evidence": {"weight_g": 180},
        "model": {"status": "SUPPORTED", "fields": ["weight_g"], "confidence": 0.68},
        "expected": "STEP_UP",  # 0.68 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_comfort_low_confidence",
        "instruction": "Comfortable for all day coding",
        "constraint": {"id": "comfort", "text": "all day coding comfort"},
        "evidence": {"earpad_type": "foam_generic"},
        "model": {"status": "SUPPORTED", "fields": ["earpad_type"], "confidence": 0.74},
        "expected": "STEP_UP",  # 0.74 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_quiet_low_confidence",
        "instruction": "Quiet listening in library",
        "constraint": {"id": "quiet_library", "text": "quiet listening in library no leakage"},
        "evidence": {"closed_back": True},
        "model": {"status": "SUPPORTED", "fields": ["closed_back"], "confidence": 0.79},
        "expected": "STEP_UP",  # 0.79 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_bass_low_confidence",
        "instruction": "Punchy energetic bass",
        "constraint": {"id": "punchy_bass", "text": "punchy energetic bass"},
        "evidence": {"driver_mm": 40},
        "model": {"status": "SUPPORTED", "fields": ["driver_mm"], "confidence": 0.65},
        "expected": "STEP_UP",  # 0.65 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_classical_low_confidence",
        "instruction": "Clear vocals for audiobooks",
        "constraint": {"id": "audiobook_vocals", "text": "clear vocals for audiobooks"},
        "evidence": {"frequency_low_hz": 20},
        "model": {"status": "SUPPORTED", "fields": ["frequency_low_hz"], "confidence": 0.71},
        "expected": "STEP_UP",  # 0.71 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_commute_low_confidence",
        "instruction": "Good for daily train commute",
        "constraint": {"id": "commute", "text": "good for daily train commute"},
        "evidence": {"wireless": True},
        "model": {"status": "SUPPORTED", "fields": ["wireless"], "confidence": 0.77},
        "expected": "STEP_UP",  # 0.77 < 0.85 -> Step-Up
    },
    {
        "name": "calibrated_abstain_work_low_confidence",
        "instruction": "Office conference calls",
        "constraint": {"id": "conf_calls", "text": "office conference calls"},
        "evidence": {"mic": True},
        "model": {"status": "SUPPORTED", "fields": ["mic"], "confidence": 0.80},
        "expected": "STEP_UP",  # 0.80 < 0.85 -> Step-Up
    },
]

total_cases = existing_cases + new_cases
cases_path.write_text(json.dumps(total_cases, indent=2), encoding="utf-8")
print(f"Total semantic benchmark cases now: {len(total_cases)}")
