import json
from pathlib import Path

ROOT = Path("d:/janus")

# 1. Create Counterfactual Dataset (25 pairs)
counterfactual_cases = [
    {
        "name": "color_metallic_vs_matte",
        "instruction": "Buy headphones. Nothing flashy.",
        "constraint": {"id": "not_flashy", "text": "nothing flashy"},
        "base_evidence": {"branding": "minimal", "weight_g": 250, "wireless": True},
        "attribute_key": "color",
        "contradicting_value": "metallic_gold",
        "supporting_value": "matte_black",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "waterproof_false_vs_true",
        "instruction": "Sweatproof and waterproof for outdoor running",
        "constraint": {"id": "waterproof", "text": "waterproof and sweatproof for running"},
        "base_evidence": {"fit": "secure_hook", "weight_g": 32},
        "attribute_key": "waterproof",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "foldable_rigid_vs_foldable",
        "instruction": "Good for travel and compact packing",
        "constraint": {"id": "travel", "text": "good for travel"},
        "base_evidence": {"travel_case": True, "weight_g": 240},
        "attribute_key": "foldable",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "battery_6h_vs_35h",
        "instruction": "Long battery life for long haul international flights",
        "constraint": {"id": "battery", "text": "long battery life for flights"},
        "base_evidence": {"anc": True, "foldable": True},
        "attribute_key": "battery_hours",
        "contradicting_value": 6,
        "supporting_value": 35,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "anc_passive_vs_hybrid",
        "instruction": "Active noise cancelling for airplane cabin noise",
        "constraint": {"id": "anc", "text": "active noise cancelling"},
        "base_evidence": {"travel_case": True, "battery_hours": 30},
        "attribute_key": "noise_cancelling",
        "contradicting_value": "passive_only",
        "supporting_value": "hybrid_anc",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "material_cheap_plastic_vs_aluminum",
        "instruction": "Premium durable metal build, not cheap brittle plastic",
        "constraint": {"id": "premium_build", "text": "premium metal build not cheap plastic"},
        "base_evidence": {"sound": "neutral", "color": "black"},
        "attribute_key": "material",
        "contradicting_value": "cheap_glossy_plastic",
        "supporting_value": "anodized_aluminum",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "lighting_rgb_vs_none",
        "instruction": "Executive look for formal video conferences, no gamer RGB lights",
        "constraint": {"id": "formal_look", "text": "formal corporate look no rgb"},
        "base_evidence": {"mic": True, "color": "dark_grey"},
        "attribute_key": "lighting",
        "contradicting_value": "rgb_pulsing",
        "supporting_value": "none",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "fit_loose_vs_secure",
        "instruction": "Must stay firmly on ears during high intensity sprint workouts",
        "constraint": {"id": "workout_fit", "text": "secure fit for sprint workouts"},
        "base_evidence": {"sweatproof": True, "weight_g": 28},
        "attribute_key": "fit",
        "contradicting_value": "loose_open_ear",
        "supporting_value": "secure_wingtip_lock",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "sound_megabass_vs_neutral",
        "instruction": "Accurate neutral studio sound for vocal recording, no bass boost",
        "constraint": {"id": "neutral_sound", "text": "neutral sound no bass boost"},
        "base_evidence": {"impedance_ohms": 80, "cable_length_m": 3.0},
        "attribute_key": "sound_tuning",
        "contradicting_value": "mega_bass_club_boost",
        "supporting_value": "flat_reference_neutral",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "case_missing_vs_included",
        "instruction": "Must come with protective hard shell carry case",
        "constraint": {"id": "case_included", "text": "includes hard shell travel case"},
        "base_evidence": {"foldable": True, "weight_g": 245},
        "attribute_key": "case_included",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "mic_none_vs_beamforming",
        "instruction": "Crystal clear microphone for client Zoom meetings",
        "constraint": {"id": "mic_quality", "text": "clear microphone for meetings"},
        "base_evidence": {"comfort": "high", "battery_hours": 20},
        "attribute_key": "mic_type",
        "contradicting_value": "none",
        "supporting_value": "dual_beamforming_noise_reduction",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "multipoint_false_vs_true",
        "instruction": "Multipoint pairing to seamlessly connect laptop and smartphone",
        "constraint": {"id": "multipoint", "text": "multipoint bluetooth connection"},
        "base_evidence": {"bluetooth_version": "5.3", "battery_hours": 25},
        "attribute_key": "multipoint",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "weight_520g_vs_210g",
        "instruction": "Ultra lightweight headphones for walking commute",
        "constraint": {"id": "lightweight", "text": "ultra lightweight for commute"},
        "base_evidence": {"foldable": True, "anc": True},
        "attribute_key": "weight_g",
        "contradicting_value": 520,
        "supporting_value": 210,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "earpads_pleather_vs_memoryfoam",
        "instruction": "Breathable cooling memory foam ear cushions for all-day comfort",
        "constraint": {"id": "breathable_cushions", "text": "breathable cooling ear cushions"},
        "base_evidence": {"clamping_force": "light", "weight_g": 230},
        "attribute_key": "cushion_material",
        "contradicting_value": "hot_sweaty_pleather",
        "supporting_value": "breathable_cooling_memory_foam",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "port_microusb_vs_usbc",
        "instruction": "Modern USB-C fast charging, absolutely no legacy micro-USB",
        "constraint": {"id": "usbc_port", "text": "modern usb-c charging no micro usb"},
        "base_evidence": {"battery_hours": 30, "fast_charge": True},
        "attribute_key": "charging_port",
        "contradicting_value": "micro_usb",
        "supporting_value": "usb_c",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "latency_320ms_vs_35ms",
        "instruction": "Low latency gaming mode for esports reaction time",
        "constraint": {"id": "low_latency", "text": "low latency for gaming"},
        "base_evidence": {"surround_sound": "7.1", "mic": True},
        "attribute_key": "latency_ms",
        "contradicting_value": 320,
        "supporting_value": 35,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "hinge_plastic_vs_metal",
        "instruction": "Durable metal reinforced folding swivel hinges",
        "constraint": {"id": "metal_hinge", "text": "durable metal reinforced hinges"},
        "base_evidence": {"foldable": True, "travel_case": True},
        "attribute_key": "hinge_type",
        "contradicting_value": "unreinforced_brittle_plastic",
        "supporting_value": "cast_steel_reinforced_swivel",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "ip_rating_none_vs_ipx5",
        "instruction": "Rated sweat resistant for heavy gym sessions",
        "constraint": {"id": "sweat_rated", "text": "rated sweat resistance for gym"},
        "base_evidence": {"fit": "in_ear_secure", "weight_g": 18},
        "attribute_key": "ip_rating",
        "contradicting_value": "none",
        "supporting_value": "IPX5",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "controls_touch_vs_physical",
        "instruction": "Physical tactile buttons so I can pause music with sweaty running gloves",
        "constraint": {"id": "physical_buttons", "text": "tactile physical buttons"},
        "base_evidence": {"waterproof": True, "volume_control": True},
        "attribute_key": "button_type",
        "contradicting_value": "capacitive_touch_only",
        "supporting_value": "tactile_physical_clickers",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "app_eq_none_vs_included",
        "instruction": "Customizable equalizer sound profile via smartphone app",
        "constraint": {"id": "eq_app", "text": "customizable eq app support"},
        "base_evidence": {"bluetooth": "5.3", "firmware_updatable": True},
        "attribute_key": "companion_app",
        "contradicting_value": "none",
        "supporting_value": "ios_android_eq_customizer",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "branding_huge_vs_discrete",
        "instruction": "Minimal discrete branding suitable for corporate executives",
        "constraint": {"id": "discrete_logo", "text": "discrete minimal branding"},
        "base_evidence": {"color": "matte_black", "finish": "satin"},
        "attribute_key": "branding",
        "contradicting_value": "oversized_neon_stencil",
        "supporting_value": "subtle_monochrome_emboss",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "transparency_none_vs_active",
        "instruction": "Transparency ambient mode to hear traffic while jogging",
        "constraint": {"id": "ambient_mode", "text": "transparency mode for outdoor safety"},
        "base_evidence": {"anc": True, "fit": "earbud"},
        "attribute_key": "ambient_mode",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "warranty_none_vs_2yr",
        "instruction": "Must have at least 1 year official manufacturer warranty",
        "constraint": {"id": "warranty", "text": "official manufacturer warranty"},
        "base_evidence": {"brand": "Northstar Audio", "condition": "new"},
        "attribute_key": "warranty_months",
        "contradicting_value": 0,
        "supporting_value": 24,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "wireless_charge_false_vs_true",
        "instruction": "Qi wireless charging support for the battery case",
        "constraint": {"id": "qi_charging", "text": "qi wireless charging case"},
        "base_evidence": {"usb_c": True, "case_included": True},
        "attribute_key": "qi_wireless_charging",
        "contradicting_value": False,
        "supporting_value": True,
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
    {
        "name": "headband_bare_vs_cushioned",
        "instruction": "Padded cushioned headband that doesn't hurt top of head",
        "constraint": {"id": "headband_cushion", "text": "cushioned headband comfort"},
        "base_evidence": {"weight_g": 220, "earcups": "soft"},
        "attribute_key": "headband_type",
        "contradicting_value": "unpadded_hard_plastic",
        "supporting_value": "plush_memory_foam_arch",
        "expected_with_contradicting": "STEP_UP",
        "expected_with_supporting": "ALLOW",
    },
]

(ROOT / "evals" / "counterfactual_cases.json").write_text(
    json.dumps(counterfactual_cases, indent=2), encoding="utf-8"
)
print(f"Wrote {len(counterfactual_cases)} counterfactual pairs to evals/counterfactual_cases.json")
